### ISSUE TITLE
Feature Request/Dark Mode

### ISSUE THREAD

**Issue by ferrellsl** [markjfine/nrsc5-dui#19]
Would it be possible to implement a dark mode?  The white window background can be particularly eye-searing in dim settings.  Maybe a black background with light gray text.  Thanks for all the work you've put into this app. I've enjoyed it immensely.  I set aside an entire mini-HTPC as my HD Radio infotainment center and placed it in my kitchen.  

![IMG_20220217_104836](https://user-images.githubusercontent.com/5926287/154540920-3552a4d2-d86f-43b3-a86f-c7ae3778b480.jpg)

**Comment by markjfine** [comment]
The light or dark mode should follow the operating system settings, however, I think I've noticed this might not be the case in Linux. I know this to be true in macOS.

I'll look into it. Might be a python setting somewhere as well.

**Comment by markjfine** [comment]
Lol. No worries. Enjoy.
