### ISSUE TITLE
Getting more unusable on small screens

### ISSUE THREAD

**Issue by andrewfer000** [markjfine/nrsc5-dui#30]
Hey Mark,

As I mentioned in a past issue at Nrsc5 DUI is getting harder to use on Lower resolution displays such as on my old laptop. 

I think there's a redesign or second layout option needed that supports wider window with shorter window height instead of this vertical style alone. 

Obviously this is an edge case so it's up to you if you think it's worth implementing. Maybe having a short and wide layout that can be enabled with a command line switch would be a good option.

**Comment by markjfine** [comment]
I have an idea what I can do but I may not be able to get to it until after the first of the year.

**Comment by markjfine** [comment]
Decided to go ahead and do it. Unzip the attached and drop it in the `res` directory. Rename to original from `mainfForm.glade` to `mainfForm1.glade`, then rename this from `mainForm2.glade` to `mainForm.glade`. You may have to resize the height a little at first because of the change in aspect ratio, but should stick after that.
[mainForm2.glade.zip](https://github.com/markjfine/nrsc5-dui/files/10278441/mainForm2.glade.zip)

**Comment by markjfine** [comment]
Also added a tentative way to switch the layout internal to the application from Settings.

**Comment by andrewfer000** [comment]
> Also added a tentative way to switch the layout internal to the application from Settings.

Much better! This works really well.

However you made a typo in the code by line 681. You have `ser_sensitive` instead of `set_sensitive`. I fixed it myself but obviously you would want that fixed before making another release.

**Comment by markjfine** [comment]
Whoops. I never hit play, so never saw it come up. Speaking of which, I should kill the nrsc5 process before restarting like that, just in case it leaves a process in limbo.

**Comment by markjfine** [comment]
Except... that would never happen if the widget was locked while it was playing... duh.

**Comment by markjfine** [comment]
Ok. Couple of other changes made to the wide mode (may have to switch then switch back to copy the new glade file in place). Let me know how it all works and if I can close this out.

**Comment by andrewfer000** [comment]
It's all good, thanks for the UI fixes.

**Comment by markjfine** [comment]
np
